# Generated by Django 2.1.5 on 2019-01-09 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic1app', '0005_imagegallery_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagegallery',
            old_name='caption',
            new_name='title',
        ),
    ]
