# Generated by Django 2.1.5 on 2019-01-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic1app', '0006_auto_20190109_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogallery',
            name='video_link',
            field=models.URLField(max_length=100),
        ),
    ]
