# Generated by Django 2.1.5 on 2019-01-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic1app', '0008_auto_20190117_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='email',
            field=models.ManyToManyField(to='clinic1app.Subscriber'),
        ),
    ]
