# Generated by Django 2.1.5 on 2019-01-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic1app', '0009_auto_20190120_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointed_date',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
