# Generated by Django 2.1.5 on 2019-01-21 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic1app', '0010_auto_20190120_1111'),
        ('clinic1app', '0009_blog_email'),
    ]

    operations = [
    ]
