# Generated by Django 2.1.5 on 2019-01-21 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic1app', '0012_auto_20190121_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointed_date',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_time', to='clinic1app.Doctor'),
        ),
    ]
