# Generated by Django 2.1.5 on 2019-01-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic1app', '0013_auto_20190122_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagedropdown',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
