# Generated by Django 2.1.5 on 2019-01-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic1app', '0014_auto_20190121_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointed_date',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
