# Generated by Django 2.1.5 on 2019-01-22 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic1app', '0015_auto_20190121_1839'),
        ('clinic1app', '0014_pagedropdown_slug'),
    ]

    operations = [
    ]
