# Generated by Django 2.1.5 on 2019-01-22 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic1app', '0016_merge_20190122_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointed_date',
            new_name='appointed_time',
        ),
    ]
