# Generated by Django 2.1.5 on 2019-01-22 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic1app', '0016_merge_20190122_1230'),
        ('clinic1app', '0017_auto_20190122_1256'),
    ]

    operations = [
    ]
