# Generated by Django 2.1.5 on 2019-01-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic1app', '0018_merge_20190122_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='mission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='vision',
            field=models.TextField(blank=True, null=True),
        ),
    ]
